#!/bin/bash

function usage()
{
  echo "    do ITEM#[, ITEM#, ITEM#, ...]"
  echo "      (customized to help you not delete recurring tasks)"
  echo "      Marks task(s) on line ITEM# as done in todo.txt."
  echo ""
  exit
}

function parse_options()
{
  local action=$1
  shift

  [ "$action" = "usage" ] && usage

  # Retrieve the item number from the arguments
  ITEM=$1
  if [[ ! "$ITEM" =~ ^[0-9]+$ ]]
  then
    error "$ITEM: invalid item number"
  exit
  fi

  shift
  ADJUST=$1
}

# Retrieve line number $ITEM from the file $TODO_FILE
function get_line()
{
  [ -f "$TODO_FILE" ] || error "$TODO_FILE: no such file"
  # Get the line from the todo file
  LINE=$(sed "$ITEM!d" "$TODO_FILE")
  [ -z "$LINE" ] && error "$ITEM: no such line"
}

parse_options "$@"
get_line

if `echo "$LINE" | grep -q " rec:"`; then
  read -r -p "This appears to be a recurring task. Are you sure? [y/N] " response
  if [[ ! $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
    echo "You should recur this task instead, using 't again'."
    exit
  fi
fi

"$TODO_SH" command do $ITEM
