#!/bin/bash
export DATE=`date +%Y%m%d`

# Don't run the filter when we list now, we'll run it in a second
export TODOTXT_DISABLE_FILTER=1
export TODOTXT_VERBOSE=0

$TODO_SH ls |
  # Keep only things that are due today or in the past
  awk '{ if ($1 <= ENVIRON["DATE"]) { print $0 } }' |
  # Run them through the color script to
  $TODO_ACTIONS_DIR/extra-color
