#!/bin/bash

if type gsed &>/dev/null; then
  SED=gsed
else
  SED=sed
fi

cat |
  # Color up anything that's overdue, also culling off those leading 8-digit
  # numbers
  awk '{
    printf "%s", ($1 < ENVIRON["DATE"] ? "\033[0;31m" : "")
    for (i = 2; i <= NF; i++) {
      printf "%s ", $i
    }
    printf "%s\n", ($1 <= ENVIRON["DATE"] ? "\033[0m" : "")
  }' |
  # Color up due and again tags, and leading numbers, and priority items
  $SED "s@\(due:[-0-9]*\)@\x1b[0;34m\1\x1b[0m@" |
  $SED "s@\(again:[+0-9mdwy]*\)@\x1b[2m\1\x1b[0m@" |
  $SED "s@^\([0-9]\+\) (A) \(.*\)\$@\1 \x1b[1;33m(A) \2\x1b[0m@" |
  $SED "s@^\([0-9]\+\) \(.* WAIT .*\)\$@\1 \x1b[2m\2\x1b[0m@" |
  $SED "s@^\([0-9]\+\) @\x1b[2m\1\x1b[0m @"
