#!/bin/bash
export DATE=`date +%Y%m%d`

cat |
  # Prepend dates, in the format 20160101, to every line with a due date
  sed 's/\(.* due:\([0-9]\{4\}\)-\([0-9]\{2\}\)-\([0-9]\{2\}\)\( .*\|$\)\)/\2\3\4 \1/' |
  # Prepend all-nines to any line without a due date
  sed '/^[0-9]\{8\}/!s/^/99999999 /' |
  # Sort by the first column, by number
  env LC_COLLATE=C sort -k1,1n -k3f
