#!/usr/bin/perl
#
# cpence: modified to spit out colored FontAwesome icons.
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';

my $acpi;
my $status;
my $percent;
my $bat_icon;
my $ac_adapt;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;

if ($percent < 12) {
	$bat_icon = '<span color="#bf616a"></span>';
} elsif ($percent < 38) {
	$bat_icon = '<span color="#d08770"></span>';
} elsif ($percent < 63) {
	$bat_icon = '<span color="#d08770"></span>';
} elsif ($percent < 87) {
	$bat_icon = '<span color="#2b303b"></span>';
} else {
	$bat_icon = '<span color="#2b303b"></span>';
}

$full_text = " ";
if ($status eq 'Discharging') {
	$full_text .= "$bat_icon ";
} elsif ($status eq 'Charging') {
	$full_text .= ' ';
} elsif ($status eq 'Unknown' or $status eq 'Full') {
	open (AC_ADAPTER, "acpi -a |") or die;
	$ac_adapt = <AC_ADAPTER>;
	close(AC_ADAPTER);

	if ($ac_adapt =~ /: ([\w-]+)/) {
		$ac_adapt = $1;

		if ($ac_adapt eq 'on-line') {
			$full_text .= ' ';
		} elsif ($ac_adapt eq 'off-line') {
			$full_text .= "$bat_icon ";
		}
	}
}

$full_text .= "$percent%";

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";

exit(0);
