#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"
if [[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
   [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
  echo "<span color='#bf616a'>‭‭</span>" # full text
fi

#------------------------------------------------------------------------

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

# color
if [[ $QUALITY -ge 80 ]]; then
  COLOR="#2b303b"
elif [[ $QUALITY -ge 60 ]]; then
  COLOR="#ebcb8b"
elif [[ $QUALITY -ge 40 ]]; then
  COLOR="#d08770"
else
  COLOR="#bf616a"
fi

#------------------------------------------------------------------------

echo "<span color='$COLOR'>‭</span> $QUALITY%" # full text
echo $QUALITY% # short text
