(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-save-default nil)
 '(auto-save-list-file-prefix nil)
 '(blink-cursor-mode nil)
 '(column-number-mode t)
 '(cua-auto-tabify-rectangles nil)
 '(cua-keep-region-after-copy t)
 '(cua-mode t nil (cua-base))
 '(current-language-environment "UTF-8")
 '(custom-enabled-themes (quote (Railscasts)))
 '(custom-safe-themes (quote ("5db6e2054777066161ba002b6ddf8c532cd40d16" default)))
 '(default-input-method nil)
 '(delete-selection-mode t)
 '(echo-keystrokes 0.01)
 '(eol-mnemonic-dos "(DOS)")
 '(eol-mnemonic-mac "(Mac)")
 '(flyspell-default-dictionary "en_US")
 '(font-lock-maximum-decoration t)
 '(font-lock-maximum-size nil)
 '(font-lock-support-mode (quote jit-lock-mode))
 '(fringe-mode 0 nil (fringe))
 '(global-font-lock-mode t)
 '(global-hl-line-mode t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-echo-area-message t)
 '(ispell-dictionary nil)
 '(ispell-extra-args (quote ("-i" "utf-8")))
 '(ispell-local-dictionary "en_US")
 '(ispell-local-dictionary-alist (quote (("en_US" "[A-za-z]" "[^A-za-z]" "'" t ("-d" "en_US") nil utf-8))))
 '(ispell-program-name "hunspell")
 '(jit-lock-contextually t)
 '(jit-lock-stealth-time 16)
 '(keyboard-coding-system (quote utf-8-unix))
 '(make-backup-files nil)
 '(recentf-max-saved-items 500)
 '(recentf-mode t)
 '(recentf-save-file "~/.emacs.d/recentf")
 '(require-final-newline t)
 '(selection-coding-system (quote utf-8))
 '(show-paren-mode t)
 '(speedbar-default-position (quote left))
 '(speedbar-show-unknown-files t)
 '(speedbar-use-images nil)
 '(standard-indent 2)
 '(tab-stop-list (quote (2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80)))
 '(tab-width 2)
 '(tool-bar-mode nil)
 '(tooltip-mode nil)
 '(transient-mark-mode t)
 '(user-full-name "Charles Pence")
 '(user-mail-address "charles@charlespence.net"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
